# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sbourgoing/dev/dpAutoRigSystem/dpAutoRigSystem/Extras/Ui/uiSpaceSwitcher.ui'
#
# Created: Mon Dec 14 11:23:20 2015
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from ...Vendor.Qt import QtCore, QtGui, QtWidgets, QtCompat

class Ui_win_main(object):
    def setupUi(self, win_main):
        win_main.setObjectName("win_main")
        win_main.resize(471, 678)
        win_main.setSizeIncrement(QtCore.QSize(0, 0))
        win_main.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(win_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_2.addWidget(self.btnRefresh)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.bottomWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomWidget.sizePolicy().hasHeightForWidth())
        self.bottomWidget.setSizePolicy(sizePolicy)
        self.bottomWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.bottomWidget.setObjectName("bottomWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bottomWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblSetupInfo = QtWidgets.QLabel(self.bottomWidget)
        self.lblSetupInfo.setObjectName("lblSetupInfo")
        self.verticalLayout.addWidget(self.lblSetupInfo)
        self.lblStatus = QtWidgets.QLabel(self.bottomWidget)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblSetupInfo_2 = QtWidgets.QLabel(self.bottomWidget)
        self.lblSetupInfo_2.setMaximumSize(QtCore.QSize(115, 16777215))
        self.lblSetupInfo_2.setObjectName("lblSetupInfo_2")
        self.horizontalLayout_3.addWidget(self.lblSetupInfo_2)
        self.cbSysList = QtWidgets.QComboBox(self.bottomWidget)
        self.cbSysList.setEditable(False)
        self.cbSysList.setModelColumn(0)
        self.cbSysList.setObjectName("cbSysList")
        self.horizontalLayout_3.addWidget(self.cbSysList)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstParent = QtWidgets.QListView(self.bottomWidget)
        self.lstParent.setModelColumn(0)
        self.lstParent.setObjectName("lstParent")
        self.horizontalLayout.addWidget(self.lstParent)
        self.btnAction = QtWidgets.QPushButton(self.bottomWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAction.sizePolicy().hasHeightForWidth())
        self.btnAction.setSizePolicy(sizePolicy)
        self.btnAction.setMinimumSize(QtCore.QSize(100, 0))
        self.btnAction.setObjectName("btnAction")
        self.horizontalLayout.addWidget(self.btnAction)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblConstraintAxis = QtWidgets.QLabel(self.bottomWidget)
        self.lblConstraintAxis.setObjectName("lblConstraintAxis")
        self.verticalLayout.addWidget(self.lblConstraintAxis)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblPosAxis = QtWidgets.QLabel(self.bottomWidget)
        self.lblPosAxis.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblPosAxis.setObjectName("lblPosAxis")
        self.horizontalLayout_4.addWidget(self.lblPosAxis)
        self.cbPosition = QtWidgets.QComboBox(self.bottomWidget)
        self.cbPosition.setObjectName("cbPosition")
        self.horizontalLayout_4.addWidget(self.cbPosition)
        self.label_2 = QtWidgets.QLabel(self.bottomWidget)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cbRotation = QtWidgets.QComboBox(self.bottomWidget)
        self.cbRotation.setObjectName("cbRotation")
        self.horizontalLayout_4.addWidget(self.cbRotation)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.bottomWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblFrameInfo = QtWidgets.QLabel(self.centralwidget)
        self.lblFrameInfo.setTextFormat(QtCore.Qt.AutoText)
        self.lblFrameInfo.setObjectName("lblFrameInfo")
        self.verticalLayout_2.addWidget(self.lblFrameInfo)
        self.tblFrameInfo = QtWidgets.QTableWidget(self.centralwidget)
        self.tblFrameInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblFrameInfo.setAutoScroll(True)
        self.tblFrameInfo.setTextElideMode(QtCore.Qt.ElideRight)
        self.tblFrameInfo.setObjectName("tblFrameInfo")
        self.tblFrameInfo.setColumnCount(3)
        self.tblFrameInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFrameInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFrameInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFrameInfo.setHorizontalHeaderItem(2, item)
        self.tblFrameInfo.horizontalHeader().setVisible(True)
        self.tblFrameInfo.horizontalHeader().setCascadingSectionResizes(True)
        self.tblFrameInfo.horizontalHeader().setMinimumSectionSize(100)
        self.tblFrameInfo.horizontalHeader().setStretchLastSection(True)
        self.tblFrameInfo.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tblFrameInfo)
        self.btnUpdateAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdateAll.setObjectName("btnUpdateAll")
        self.verticalLayout_2.addWidget(self.btnUpdateAll)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        win_main.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(win_main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 471, 25))
        self.menuBar.setObjectName("menuBar")
        win_main.setMenuBar(self.menuBar)

        self.retranslateUi(win_main)
        QtCore.QMetaObject.connectSlotsByName(win_main)

    def retranslateUi(self, win_main):
        win_main.setWindowTitle(QtCompat.translate("win_main", "Space Switcher", None, -1))
        self.btnRefresh.setText(QtCompat.translate("win_main", "Refresh Tool", None, -1))
        self.lblSetupInfo.setText(QtCompat.translate("win_main", "<b>Parent Info</b>", None, -1))
        self.lblStatus.setText(QtCompat.translate("win_main", "Current Mode --> <b>Inactive</b>", None, -1))
        self.lblSetupInfo_2.setText(QtCompat.translate("win_main", "Selected System:", None, -1))
        self.btnAction.setText(QtCompat.translate("win_main", "Setup", None, -1))
        self.lblConstraintAxis.setText(QtCompat.translate("win_main", "Constrained Axis", None, -1))
        self.lblPosAxis.setText(QtCompat.translate("win_main", "Position:", None, -1))
        self.label_2.setText(QtCompat.translate("win_main", "Rotation:", None, -1))
        self.lblFrameInfo.setText(QtCompat.translate("win_main", "<b>Frame/Constraint Info</b>", None, -1))
        self.tblFrameInfo.setSortingEnabled(True)
        self.tblFrameInfo.horizontalHeaderItem(0).setText(QtCompat.translate("win_main", "Frame", None, -1))
        self.tblFrameInfo.horizontalHeaderItem(1).setText(QtCompat.translate("win_main", "Parent", None, -1))
        self.tblFrameInfo.horizontalHeaderItem(2).setText(QtCompat.translate("win_main", "Action", None, -1))
        self.btnUpdateAll.setText(QtCompat.translate("win_main", "Update All Constraints", None, -1))

